name: deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Deploy React code to GitHub Pages
  # You may pin to the exact commit or the version.
  # uses: amitsingh-007/deploy-to-github-pages@bb129748a26581f82d132db7ca88eac4b1651b36
        uses: amitsingh-007/deploy-to-github-pages@v1.2

      - name: Build web-app
        run: |
          npm ci
          run: npm install
          npm run build --if-present
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build
          allow_empty_commit: true
